### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by mrjoelkemp** [mrjoelkemp/Dependents#122]
Might be fixed with #120 

```
reloading plugin Dependents.TreeCommand
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 73, in reload_plugin
    m = importlib.import_module(modulename)
  File "./importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 584, in _check_name_wrapper
  File "<frozen importlib._bootstrap>", line 1022, in load_module
  File "<frozen importlib._bootstrap>", line 1003, in load_module
  File "<frozen importlib._bootstrap>", line 560, in module_for_loader_wrapper
  File "<frozen importlib._bootstrap>", line 868, in _load_module
  File "<frozen importlib._bootstrap>", line 313, in _call_with_frames_removed
  File "C:\Users\mrjoelkemp\AppData\Roaming\Sublime Text 3\Packages\Dependents\TreeCommand.py", line 8, in <module>
    from .BaseCommand import BaseCommand
  File "C:\Users\mrjoelkemp\AppData\Roaming\Sublime Text 3\Packages\Dependents\BaseCommand.py", line 5, in <module>
    from .lib.command_setup import command_setup
  File "C:\Users\mrjoelkemp\AppData\Roaming\Sublime Text 3\Packages\Dependents\lib\command_setup.py", line 5, in <module>
    from .track import track as t
  File "C:\Users\mrjoelkemp\AppData\Roaming\Sublime Text 3\Packages\Dependents\lib\track.py", line 1, in <module>
    from ..vendor.Mixpanel import *
ImportError: No module named 'Dependents.vendor'
```

**Comment by mrjoelkemp** [comment]
Fixed with Master
