### ISSUE TITLE
Find Dependents throws on ES6 codebase

### ISSUE THREAD

**Issue by mrjoelkemp** [mrjoelkemp/Dependents#165]
```
Error: 
/Users/jokemp/Library/Application Support/Sublime Text 3/Packages/Dependents/node_modules/dependents/node_modules/resolve-dependency-path/index.js:11
  if (!dep) { throw new Error('dependency path not given'); }
                    ^
Error: dependency path not given
    at module.exports (/Users/jokemp/Library/Application Support/Sublime Text 3/Packages/Dependents/node_modules/dependents/node_modules/resolve-dependency-path/index.js:11:21)
    at /Users/jokemp/Library/Application Support/Sublime Text 3/Packages/Dependents/node_modules/dependents/lib/computeDependents.js:47:13
    at Array.forEach (native)
    at module.exports (/Users/jokemp/Library/Application Support/Sublime Text 3/Packages/Dependents/node_modules/dependents/lib/computeDependents.js:32:16)
    at /Users/jokemp/Library/Application Support/Sublime Text 3/Packages/Dependents/node_modules/dependents/index.js:92:19
    at Array.forEach (native)
    at dependents (/Users/jokemp/Library/Application Support/Sublime Text 3/Packages/Dependents/node_modules/dependents/index.js:91:9)
    at Object.<anonymous> (/Users/jokemp/Library/Application Support/Sublime Text 3/Packages/Dependents/node_modules/dependents/bin/dependents.js:32:1)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
```

**Comment by mrjoelkemp** [comment]
Related to #166. Was due to an incorrect require config
